apl: apl
ast: asterisk
cs: clike
c: clike
cpp: clike
java: clike
clj: clojure
cob: cobol
coffee: coffeescript
iced: coffeescript
lisp: commonlisp
css: css
d: d
diff: diff
dtd: dtd
ecl: ecl
eiffel: eiffel
erl: erlang
for: fortran
gas: gas
gfm: gfm
gh: gherkin
go: go
gr: groovy
haml: haml
hs: haskell
haxe: haxe
html: htmlmixed
http: http
jade: jade
js: javascript
jinja2: jinja2
julia: julia
less: less
ls: livescript
lua: lua
md: markdown
meta: meta.js
mirc: mirc
ml: mllike
nginx: nginx
nt: ntriples
oct: octave
pas: pascal
pegjs: pegjs
pl: perl
php: php
pig: pig
prop: properties
py: python
q: q
r: r
rpm: rpm
rst: rst
rb: ruby
rust: rust
sass: sass
scm: scheme
sh: shell
si: sieve
st: smalltalk
sm: smartymixed
spq: sparql
sql: sql
stex: stex
tcl: tcl
tiddly: tiddlywiki
tiki: tiki
toml: toml
turtle: turtle
vb: vb
vbscript: vbscript
vel: velocity
vl: verilog
xml: xml
xq: xquery
yml: yaml
yaml: yaml
z80: z80
